### ISSUE TITLE
Scalebar support

### ISSUE THREAD

**Issue by joakimlindblad** [MIDA-group/CytoBrowser#110]
https://pages.nist.gov/OpenSeadragonScalebar/

**Comment by wdj577** [comment]
How to calculate the ratio of pixels to actual  ‘pixelsPerMeter：  what?’
`
 console.log(that.viewer.tileSources.Image.Size.Width)
        this.viewer.scalebar({
          type: this.$OpenSeadragon.ScalebarType.MAP,
          pixelsPerMeter: 38400, // ？？？？？？？？？？？？？？？？
          // pixelsPerMeter: 1000 * that.viewer.tileSources.Image.Size.Width //
          minWidth: "150px",
          location: this.$OpenSeadragon.ScalebarLocation.BOTTOM_LEFT,
          xOffset: 10,
          yOffset: 10,
          stayInsideImage: false,
          color: "rgb(0, 0, 0)",
          fontColor: "rgb(0, 0, 0)",
          backgroundColor: "rgba(255, 255, 255, 0.5)",
          fontSize: "middle",
          barThickness: 4,
        });
`

**Comment by joakimlindblad** [comment]
I am not sure I understand the question. What is it that you wish to achieve?


pixelsPerMeter for the Scale bar is computed from Metadata (in metadataHandler.js) using PhysicalSizeXUnit and PhysicalSizeX

which are typically read from a json file, e.g., as follows:
```
~/CytoBrowser $ cat metadata/json/patient\ X.json
{
    "AcquisitionDate": "2021-01-31T10:00:49",
    "PhysicalSizeX": 0.2,
    "PhysicalSizeY": 0.2,
    "PhysicalSizeXUnit": "µm",
    "PhysicalSizeYUnit": "µm",
    "SignificantBits": 8,
    "SizeC": 3,
    "SizeX": 127989,
    "SizeY": 119548,
    "SizeZ": 8
}
```
