### ISSUE TITLE
Sometimes when switching to new session, 0 annotations gets loaded

### ISSUE THREAD

**Issue by joakimlindblad** [MIDA-group/CytoBrowser#232]
Possible race condition? 
Seems the server hasn't loaded annotations, but responds to "summary" request with 0 annotations.

**Comment by joakimlindblad** [comment]
Possibly missing 'this.ongoingLoad.then' on "requestSummary" message received by server

**Comment by crydell** [comment]
This looks like a correct solution to me. Looks like you're right in that the summary request could come before the ongoing load finishes before this commit, I would assume it became more apparent with a larger annotation file taking longer to load.
